### ISSUE TITLE
HypeMan is not playing even allowed on voice channel

### ISSUE THREAD

**Issue by mikeemoves** [georgielang/HypeManFiles#1]
Hello, I simply noticed that our hypeman bot on our server is not working. it happens last week. we saw the bot has stayed on our channel. and now, I've tried to rejoin it but had no luck playing our audio. but we can use the commands.

**Comment by Tebinski** [comment]
Let me know if I can help

**Comment by mikeemoves** [comment]
Hi @Tebinski , Like I discussed above, is there a solution to make the bot work again?. I've tried to kick and invite it on server but still no luck

**Comment by mikeemoves** [comment]
this is now working. thank you
