### ISSUE TITLE
The bot not play intro music

### ISSUE THREAD

**Issue by Developperhuman2300** [georgielang/HypeManFiles#2]
Hello 
The bot i have on the discord server will not play music when we join channel's it's just connect and disconnect after 10 sec 

Any status of maintanse or something? about the bot so i can explane it to they others?

**Comment by Developperhuman2300** [comment]
it's workning now.

**Comment by georgielang** [comment]
There seems to be an underlying problem regarding the bot in some very specific servers doing this from time to time, I will be working on it but a simple restart on the bots end seems to fix it for every server, so I'm glad its working for you now!
